Feature/searchbar autosuggest
ernerdo/movie-series pull request #22
Opened 2023-09-09 19:24 UTC by darkusphantom

2023-09-10 00:38 UTC, ernerdo requested changes

2023-09-10 00:38 UTC, ernerdo commented on src/components/Searchbar/Searchbar.tsx
> +        {console.log(inputItems)}
remove console .og

2023-09-10 00:38 UTC, ernerdo commented on src/components/Searchbar/Searchbar.tsx
>  const Searchbar = () => {
usar camelcase, eso aplica para el nombre del folder y para el componente.

2023-09-10 00:38 UTC, ernerdo commented on src/components/Searchbar/Searchbar.tsx
> +  const [inputItems, setInputItems] = useState<any[]>([])
no usemos any, apliquemos el tipo o podriamos usar unknown

2023-09-10 01:31 UTC, darkusphantom commented on src/components/Searchbar/Searchbar.tsx
>  const Searchbar = () => {
Está aplicando camelcase 🤔 . Solo que la funcion utiliza la miniscula al iniciar y el folder en cada palabra

¿Qué regla para escribir los folders y funciones se puede aplicar? 🤔

2023-09-10 01:34 UTC, ernerdo commented on src/components/Searchbar/Searchbar.tsx
>  const Searchbar = () => {
el fonder debe ser SearchBar y el componente SearchBar, aca me refiero a PascalCase para los componentes y folder.

2023-09-11 01:51 UTC, ernerdo approved these changes

2023-09-14 13:51 UTC, merged